(function() {
'use strict';
const C=window.JaneMDaily, A=window.JaneMDailyArt, R=window.JaneMRunway, $=id=>document.getElementById(id);
const key='janem-daily-style-v1'; let persistent=true, state;
try {state=C.normalise(JSON.parse(localStorage.getItem(key)||'null'));}catch {state=C.normalise(null);persistent=false;}
let today=C.dateKey(), day=today, chosen={}, slot='look', revealed=false, started=new Set();
let motionOff=false;
try {motionOff=localStorage.getItem('janem-daily-motion')==='off';}catch{}
const systemReduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true;
function motionPreference(){document.body.dataset.motion=motionOff?'off':'on';$('motion-toggle').setAttribute('aria-pressed',String(motionOff));$('motion-toggle').textContent=systemReduced()?'Reduced motion (device setting)':motionOff?'Enable motion':'Reduce motion';$('motion-toggle').disabled=systemReduced();if($('replay-reveal'))$('replay-reveal').disabled=motionOff||systemReduced();}
motionPreference();
window.matchMedia?.('(prefers-reduced-motion: reduce)').addEventListener?.('change',motionPreference);
$('motion-toggle').addEventListener('click',()=>{motionOff=!motionOff;try{localStorage.setItem('janem-daily-motion',motionOff?'off':'on');}catch{} if(motionOff)document.getAnimations?.().forEach(a=>a.cancel());motionPreference();if($('replay-reveal'))$('replay-reveal').disabled=motionOff||systemReduced();});
function animate(el,frames,options={}){if(el?.animate&&!motionOff&&!systemReduced())el.animate(frames,{duration:380,easing:'cubic-bezier(.2,.8,.2,1)',...options});}
function enterOptions(){document.querySelectorAll('.piece-option').forEach((el,i)=>animate(el,[{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{delay:i*30}));}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const track=(event,detail={})=>window.JaneMAnalytics?.track(event,{challenge_id:C.challenge(day).id,...detail});
const pretty=d=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
function save() {try{localStorage.setItem(key,JSON.stringify(state));persistent=true;}catch{persistent=false;} $('storage-note').textContent=persistent?'':'Your browser cannot save progress right now. You can still play and download your style card.';}
function visit() {if(!state.visits.includes(today)){const previous=state.visits.filter(d=>d<today).sort().pop();track('daily_style_visit',{return_gap_days:previous?C.dayNumber(today)-C.dayNumber(previous):0,returning_player:!!previous});state.visits.push(today);state.visits=state.visits.slice(-180);save();}}
function renderProgress() {const stats=C.stats(state,today);$('saved-count').textContent=stats.total;$('progress').innerHTML=`<div><strong>${stats.total}</strong><span>brief${stats.total===1?'':'s'} played</span></div><div><strong>${stats.streak}</strong><span>day${stats.streak===1?'':'s'} in a row</span></div><div class="week-dots" aria-label="Last seven days">${stats.week.map(d=>`<span class="${d.done?'done':''}" title="${pretty(d.date)}${d.done?': played':': not played'}" aria-label="${pretty(d.date)}${d.done?': played':': not played'}">${d.done?'✓':'·'}</span>`).join('')}</div>`;}
function picker() {const dates=Array.from({length:7},(_,i)=>C.shift(today,-i));if(!dates.includes(day))dates.push(day);$('brief-picker').innerHTML=dates.map(d=>`<option value="${d}" ${d===day?'selected':''}>${d===today?'Today':pretty(d)} · ${esc(C.challenge(d).title)}</option>`).join('');}
function load(d) {day=d;chosen=C.selection(state.drafts[d]||state.results[d]?.selection);slot=C.slots.find(s=>!chosen[s])||'look';revealed=false;const c=C.challenge(day);$('brief-number').textContent=`BRIEF ${String(c.number).padStart(2,'0')} / 30`;$('brief-date').textContent=day===today?'TODAY · '+pretty(day):pretty(day);$('brief-date').dateTime=day;$('brief-title').textContent=c.title;$('brief-scene').textContent=c.scene;$('brief-goals').innerHTML=c.goals.map((g,i)=>`<li><span>${i+1}</span>${esc(g.label)}</li>`).join('');$('game-result').hidden=true;picker();renderChoice();}
function renderChoice() {
 $('selection-count').textContent=`${Object.keys(chosen).length} of 4 pieces`;
 $('outfit-preview').innerHTML=C.slots.map(s=>{const p=C.pieces.find(p=>p.id===chosen[s]);return `<button type="button" class="preview-piece ${p?'filled':''}" data-select-slot="${s}" aria-label="${esc(p?'Change '+p.name:'Choose '+C.labels[s])}">${p?A.svg(p):'<span class="piece-placeholder" aria-hidden="true">+</span>'}<span>${esc(p?p.name:C.labels[s])}</span></button>`;}).join('');
 $('slot-tabs').innerHTML=C.slots.map((s,i)=>`<button type="button" role="tab" id="slot-${s}" aria-controls="piece-options" aria-selected="${s===slot}" tabindex="${s===slot?'0':'-1'}" data-slot="${s}"><span aria-hidden="true">${chosen[s]?'✓':i+1}</span>${C.labels[s]}</button>`).join('');
 $('piece-options').setAttribute('aria-labelledby','slot-'+slot);
 $('piece-options').innerHTML=`<fieldset><legend class="visually-hidden">${C.labels[slot]} choices</legend><div class="piece-options-grid ${slot==='look'?'':'four-options'}">${C.pieces.filter(p=>p.slot===slot).map(p=>`<label class="piece-option ${chosen[slot]===p.id?'selected':''}"><input type="radio" name="piece-${slot}" value="${p.id}" ${chosen[slot]===p.id?'checked':''}><span class="option-art">${A.svg(p)}<span class="option-tick" aria-hidden="true">✓</span></span><strong>${esc(p.name)}</strong><small>${esc(p.note)}</small></label>`).join('')}</div></fieldset>`;
 const index=C.slots.indexOf(slot);$('next-slot').hidden=index===3;$('next-slot').textContent='Next: '+C.labels[C.slots[index+1]]+' →';$('check-look').disabled=Object.keys(chosen).length!==4;$('check-look').textContent=Object.keys(chosen).length===4?'Reveal my look ✦':`Choose ${4-Object.keys(chosen).length} more piece${Object.keys(chosen).length===3?'':'s'} to reveal`;
}
function selectSlot(s,focus=false) {const changed=slot!==s;slot=s;renderChoice();if(changed)enterOptions();if(focus)$('slot-'+s).focus();}
$('slot-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-slot]');if(b)selectSlot(b.dataset.slot,true);});
$('slot-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=C.slots.indexOf(slot);i=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;selectSlot(C.slots[i],true);});
$('outfit-preview').addEventListener('click',e=>{const b=e.target.closest('[data-select-slot]');if(b)selectSlot(b.dataset.selectSlot,true);});
$('piece-options').addEventListener('change',e=>{if(!e.target.matches('input[type="radio"]'))return;const p=C.pieces.find(p=>p.id===e.target.value&&p.slot===slot);if(!p)return;if(!started.has(day)){track('daily_style_start',{is_today:day===today});started.add(day);}chosen[slot]=p.id;state.drafts[day]={...chosen};save();revealed=false;$('game-result').hidden=true;renderChoice();animate(document.querySelector(`[data-select-slot="${slot}"] svg`),[{opacity:0,transform:'translateY(-16px) rotate(-7deg) scale(.85)'},{opacity:1,transform:'translateY(0) rotate(0) scale(1)'}]);animate(document.querySelector('.piece-option.selected .option-tick'),[{transform:'scale(.2)'},{transform:'scale(1.15)',offset:.7},{transform:'scale(1)'}]);document.querySelector(`input[value="${p.id}"]`).focus();});
$('jump-to-pieces').addEventListener('click',()=>{selectSlot(slot,true);$('slot-tabs').scrollIntoView({block:'start'});});
$('next-slot').addEventListener('click',()=>selectSlot(C.slots[Math.min(3,C.slots.indexOf(slot)+1)],true));
$('clear-look').addEventListener('click',()=>{chosen={};state.drafts[day]={};save();slot='look';revealed=false;$('game-result').hidden=true;renderChoice();$('slot-look').focus();});
$('brief-picker').addEventListener('change',e=>{load(e.target.value);$('brief-title').setAttribute('tabindex','-1');$('brief-title').focus();});
let layerVisible=true;
function animateOutfit(){
 const host=$('runway-outfit');host.getAnimations?.({subtree:true}).forEach(a=>a.cancel());
 for(const [i,part] of ['figure','look','shoes','layer','finish'].entries())animate(host.querySelector(`[data-outfit-part="${part}"]`),[{opacity:0,transform:`translateY(${part==='figure'?0:12}px)`},{opacity:1,transform:'translateY(0)'}],{duration:500,delay:i*180,fill:'backwards'});
 animate(host.querySelector('.outfit-figure'),[{transform:'rotate(-1deg)'},{transform:'rotate(0deg)'}],{duration:1600});
}
function renderOutfit(play=true){
 $('runway-outfit').innerHTML=R.outfit(chosen,{layerVisible});
 $('runway-pieces').innerHTML=C.slots.map(slot=>{const p=C.pieces.find(p=>p.id===chosen[slot]);return `<li><span class="runway-swatch" style="background:${p.colour}" aria-hidden="true"></span><span><small>${C.labels[slot]}</small>${esc(p.name)}</span></li>`;}).join('');
 $('toggle-layer').setAttribute('aria-pressed',String(layerVisible));$('toggle-layer').textContent=layerVisible?'View without layer':'View with layer';
 $('replay-reveal').disabled=motionOff||systemReduced();if(play)animateOutfit();
}
$('replay-reveal').addEventListener('click',()=>{if(revealed){$('runway-outfit').scrollIntoView?.({block:'start',behavior:'instant'});animateOutfit();}});
$('toggle-layer').addEventListener('click',()=>{if(!revealed)return;layerVisible=!layerVisible;renderOutfit(false);$('runway-outfit').scrollIntoView?.({block:'start',behavior:'instant'});});
function reveal() {rollover();const c=C.challenge(day),s=C.score(c,chosen);if(!s.complete)return;const first=!state.results[day];state=C.record(state,day,chosen);save();renderProgress();revealed=true;layerVisible=true;$('game-result').hidden=false;renderOutfit();$('result-medallion').style.setProperty('--score',s.points);$('result-medallion').firstElementChild.textContent=s.points+' / 4';$('result-title').textContent=s.points===4?'Brief beautifully met.':`${s.points} of 4 details met.`;$('result-copy').textContent=s.points===4?'Your choices meet every part of this brief. Keep the look, or explore another combination.':'Your look is yours. To meet more of this particular brief, use the notes below and try a swap.';$('result-checks').innerHTML=s.checks.map(g=>`<li class="${g.met?'met':''}"><span aria-hidden="true">${g.met?'✓':'○'}</span><span>${esc(g.label)}${!g.met?`<small>${g.slot==='shoes'?'Try different shoes.':'Try a different '+C.labels[g.slot].toLowerCase().replace(/^the |^a /,'')+'.'}</small>`:''}</span></li>`).join('');$('style-tip').textContent=c.tip;$('return-note').textContent=day===today?`Tomorrow: “${C.challenge(C.shift(today,1)).title}”. A new brief at midnight (UTC+2).`:'Today’s brief is ready when you are. Find it in the recent briefs menu.';$('enquire-look').href='https://wa.me/26662790946?text='+encodeURIComponent(`Hello Jane.M, I tried the Daily Style brief “${c.title}”. My direction was ${C.slots.map(s=>C.pieces.find(p=>p.id===chosen[s]).name).join(', ')}. I would like to discuss a custom look for my occasion.`);$('share-status').textContent='';$('share-fallback').hidden=true;track(first?'daily_style_complete':'daily_style_retry',{score:s.points,is_today:day===today});$('game-result').focus();$('game-result').scrollIntoView?.({block:'start',behavior:'instant'});animate($('game-result'),[{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}]);animate($('result-medallion'),[{transform:'scale(.7) rotate(-15deg)'},{transform:'scale(1) rotate(0)'}],{duration:550});document.querySelectorAll('#result-checks li').forEach((el,i)=>animate(el,[{opacity:0,transform:'translateX(-8px)'},{opacity:1,transform:'translateX(0)'}],{delay:150+i*90}));}
$('check-look').addEventListener('click',reveal);
$('retry-look').addEventListener('click',()=>{const failed=C.score(C.challenge(day),chosen).checks.find(g=>!g.met);selectSlot(failed?.slot||'look',true);$('game-result').hidden=true;revealed=false;});
function view(name,focus=false) {for(const n of ['today','saved','how']){ $(n+'-view').hidden=n!==name;document.querySelector(`[data-view="${n}"]`).setAttribute('aria-pressed',String(n===name));}if(name==='saved')renderSaved();if(focus&&name!=='today')$(name==='saved'?'lookbook-title':'how-title').focus();}
document.querySelector('.game-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)view(b.dataset.view,true);});
for(const id of ['back-today','start-playing'])$(id).addEventListener('click',()=>{load(today);view('today');$('slot-'+slot).focus();});
function renderSaved() {const stats=C.stats(state,today);$('milestones').innerHTML=[[1,'First look'],[5,'Style explorer'],[10,'Detail finder'],[30,'Thirty moments']].map(([n,label])=>`<span class="${stats.total>=n?'earned':''}">${stats.total>=n?'✦':'○'} ${label}<small>${Math.min(n,stats.total)} / ${n} briefs</small></span>`).join('');const dates=Object.keys(state.results).filter(d=>d<=today).sort().reverse();$('saved-grid').innerHTML=dates.length?dates.map(d=>{const r=state.results[d];return `<article class="saved-look"><div class="saved-art saved-outfit">${R.outfit(r.selection)}</div><p class="eyebrow">${pretty(d)} · ${r.points}/4 DETAILS</p><h3>${esc(C.challenge(d).title)}</h3><button type="button" data-replay="${d}">Revisit this look →</button></article>`;}).join(''):'<div class="empty-lookbook"><span aria-hidden="true">✦</span><h3>Your first look starts here.</h3><p>Complete a brief to save your outfit and begin your style diary.</p></div>';}
$('saved-grid').addEventListener('click',e=>{const b=e.target.closest('[data-replay]');if(b){load(b.dataset.replay);view('today');$('slot-'+slot).focus();}});
function shareText(){const c=C.challenge(day),s=C.score(c,chosen);return `Jane.M Daily Style · ${pretty(day)}\n${c.title}\n${s.checks.map(g=>g.met?'✦':'○').join(' ')} ${s.points}/4 details\nYour turn: https://wearjanem.com/daily-style/?utm_source=player_share&utm_medium=social&utm_campaign=daily_style`;}
$('share-look').addEventListener('click',async()=>{if(!revealed)return;const text=shareText();try{if(navigator.share){await navigator.share({title:'Jane.M Daily Style',text});$('share-status').textContent='Result shared.';track('daily_style_share',{method:'native'});}else if(navigator.clipboard){await navigator.clipboard.writeText(text);$('share-status').textContent='Copied. Paste your result into WhatsApp or a message.';track('daily_style_share',{method:'copy'});}else throw Error('Copy unavailable');}catch(e){if(e.name==='AbortError')return;$('share-fallback').hidden=false;$('share-fallback').value=text;$('share-fallback').select();$('share-status').textContent='Select and copy this result to share it.';}});
function download(blob,name) {const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.hidden=true;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('download-look').addEventListener('click',async()=>{if(!revealed)return;const snapshot={day,chosen:{...chosen}};const button=$('download-look');button.disabled=true;try{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');ctx.fillStyle='#fbf8f3';ctx.fillRect(0,0,1080,1350);ctx.strokeStyle='#b38a45';ctx.lineWidth=2;ctx.strokeRect(36,36,1008,1278);ctx.fillStyle='#15120f';ctx.font='52px Georgia';ctx.fillText('Jane.M',80,120);ctx.fillStyle='#8f682e';ctx.font='20px Arial';ctx.fillText('DAILY STYLE  /  '+pretty(snapshot.day).toUpperCase(),80,166);ctx.fillStyle='#15120f';ctx.font='54px Georgia';ctx.fillText(C.challenge(snapshot.day).title,80,250,920);ctx.font='23px Arial';ctx.fillStyle='#756a5f';ctx.fillText('My four-piece style moment',80,300);
const image=new Image();image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(R.outfit(snapshot.chosen));await image.decode();ctx.fillStyle='#f1e9de';ctx.fillRect(80,345,570,740);ctx.drawImage(image,155,350,420,722);
for(let i=0;i<4;i++){const p=C.pieces.find(p=>p.id===snapshot.chosen[C.slots[i]]),y=450+i*135;ctx.fillStyle=p.colour;ctx.beginPath();ctx.arc(707,y-8,9,0,Math.PI*2);ctx.fill();ctx.font='17px Arial';ctx.fillStyle='#8f682e';ctx.fillText(C.labels[C.slots[i]].toUpperCase(),730,y-16);ctx.font='23px Georgia';ctx.fillStyle='#15120f';ctx.fillText(p.name,690,y+25,310);}
ctx.font='32px Georgia';ctx.fillStyle='#8f682e';ctx.fillText(`${C.score(C.challenge(snapshot.day),snapshot.chosen).points} / 4 brief details met`,80,1160);ctx.font='22px Arial';ctx.fillStyle='#15120f';ctx.fillText('Play your daily brief at wearjanem.com/daily-style/',80,1220);ctx.font='17px Arial';ctx.fillStyle='#756a5f';ctx.fillText('Illustrated styling ideas · Wear your imagination.',80,1264);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('No image');download(blob,`janem-daily-style-${snapshot.day}.png`);$('share-status').textContent='Your style card is ready in your downloads.';track('daily_style_card_download');}catch{$('share-status').textContent='The image could not be saved. You can still share your text result.';}finally{button.disabled=false;}});
$('export-progress').addEventListener('click',()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'janem-daily-style-progress.json'));
$('clear-progress').addEventListener('click',()=>$('clear-game-dialog').showModal());$('cancel-clear').addEventListener('click',()=>$('clear-game-dialog').close());$('confirm-clear').addEventListener('click',()=>{state=C.normalise(null);save();load(today);renderProgress();renderSaved();$('clear-game-dialog').close();});
function rollover() {const next=C.dateKey();if(next===today)return;today=next;visit();picker();renderProgress();if(revealed)$('return-note').textContent='A new brief is ready. Choose Today in the recent briefs menu.';}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)rollover();});setInterval(rollover,60000);
window.addEventListener('storage',e=>{if(e.key===key){try{state=C.normalise(JSON.parse(e.newValue));renderProgress();if(!$('saved-view').hidden)renderSaved();}catch{}}});
load(today);visit();renderProgress();save();
})();
