(function() {
'use strict';
const C=window.JaneMDaily, A=window.JaneMDailyArt, R=window.JaneMRunway, $=id=>document.getElementById(id);
const key='janem-daily-style-v1'; let persistent=true, state;
try {state=C.normalise(JSON.parse(localStorage.getItem(key)||'null'));}catch {state=C.normalise(null);persistent=false;}
let today=C.dateKey(), day=today, chosen={}, slot='look', revealed=false, started=new Set();
let motionOff=false;
try {motionOff=localStorage.getItem('janem-daily-motion')==='off';}catch{}
const systemReduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true;
function motionPreference(){document.body.dataset.motion=motionOff?'off':'on';$('motion-toggle').setAttribute('aria-pressed',String(motionOff));$('motion-toggle').textContent=systemReduced()?'Reduced motion (device setting)':motionOff?'Enable motion':'Reduce motion';$('motion-toggle').disabled=systemReduced();if($('replay-reveal'))$('replay-reveal').disabled=motionOff||systemReduced();}
motionPreference();
window.matchMedia?.('(prefers-reduced-motion: reduce)').addEventListener?.('change',motionPreference);
$('motion-toggle').addEventListener('click',()=>{motionOff=!motionOff;try{localStorage.setItem('janem-daily-motion',motionOff?'off':'on');}catch{} if(motionOff)document.getAnimations?.().forEach(a=>a.cancel());motionPreference();if($('replay-reveal'))$('replay-reveal').disabled=motionOff||systemReduced();});
function animate(el,frames,options={}){if(el?.animate&&!motionOff&&!systemReduced())el.animate(frames,{duration:380,easing:'cubic-bezier(.2,.8,.2,1)',...options});}
function enterOptions(){document.querySelectorAll('.piece-option').forEach((el,i)=>animate(el,[{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{delay:i*30}));}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const track=(event,detail={})=>window.JaneMAnalytics?.track(event,{challenge_id:C.challenge(day).id,...detail});
const pretty=d=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
function save() {try{localStorage.setItem(key,JSON.stringify(state));persistent=true;}catch{persistent=false;} $('storage-note').textContent=persistent?'':'Your browser cannot save progress right now. You can still play and download your style card.';}
function visit() {if(!state.visits.includes(today)){const previous=state.visits.filter(d=>d<today).sort().pop();track('daily_style_visit',{return_gap_days:previous?C.dayNumber(today)-C.dayNumber(previous):0,returning_player:!!previous});state.visits.push(today);state.visits=state.visits.slice(-180);save();}}
function renderProgress() {const stats=C.stats(state,today);$('saved-count').textContent=stats.total;$('header-streak').textContent=stats.streak;const c=C.challenge(today);$('home-brief-title').textContent=c.title;$('home-scene').textContent=c.scene;$('play-spark').firstChild.textContent=state.results[today]?'Play today’s Spark again ':'Play today’s Spark '; $('progress').innerHTML=`<div><strong>${stats.total}</strong><span>brief${stats.total===1?'':'s'} played</span></div><div><strong>${stats.streak}</strong><span>day${stats.streak===1?'':'s'} in a row</span></div><div class="week-dots" aria-label="Last seven days">${stats.week.map(d=>`<span class="${d.done?'done':''}" title="${pretty(d.date)}${d.done?': played':': not played'}" aria-label="${pretty(d.date)}${d.done?': played':': not played'}">${d.done?'✓':'·'}</span>`).join('')}</div>`;}
function picker() {const dates=Array.from({length:7},(_,i)=>C.shift(today,-i));if(!dates.includes(day))dates.push(day);$('brief-picker').innerHTML=dates.map(d=>`<option value="${d}" ${d===day?'selected':''}>${d===today?'Today':pretty(d)} · ${esc(C.challenge(d).title)}</option>`).join('');}
function load(d) {day=d;chosen=C.selection(state.drafts[d]||state.results[d]?.selection);slot=C.slots.find(s=>!chosen[s])||'look';revealed=false;const c=C.challenge(day);$('brief-number').textContent=`BRIEF ${String(c.number).padStart(2,'0')} / 30`;$('brief-date').textContent=day===today?'TODAY · '+pretty(day):pretty(day);$('brief-date').dateTime=day;$('brief-title').textContent=c.title;$('brief-scene').textContent=c.scene;$('brief-goals').innerHTML=c.goals.map((g,i)=>`<li><span>${i+1}</span>${esc(g.label)}</li>`).join('');$('game-result').hidden=true;$('builder-layout').hidden=false;document.querySelector('.game-brief').hidden=false;picker();renderChoice();}
function renderChoice() {
 const liveScore=C.score(C.challenge(day),chosen);$('live-outfit').innerHTML=R.outfit(chosen);$('fit-score').textContent=liveScore.points+' / 4';$('cohesion-meter').value=liveScore.points;$('live-caption').textContent=Object.keys(chosen).length?'Looking good. Keep playing with your four pieces.':'Start with a look. Thandi’s ready for your ideas.';document.querySelectorAll('#brief-goals li').forEach((el,i)=>el.classList.toggle('met',liveScore.checks[i].met));
 $('selection-count').textContent=`${Object.keys(chosen).length} of 4 pieces`;
 $('outfit-preview').innerHTML=C.slots.map(s=>{const p=C.pieces.find(p=>p.id===chosen[s]);return `<button type="button" class="preview-piece ${p?'filled':''}" data-select-slot="${s}" aria-label="${esc(p?'Change '+p.name:'Choose '+C.labels[s])}">${p?A.svg(p):'<span class="piece-placeholder" aria-hidden="true">+</span>'}<span>${esc(p?p.name:C.labels[s])}</span></button>`;}).join('');
 $('slot-tabs').innerHTML=C.slots.map((s,i)=>`<button type="button" role="tab" id="slot-${s}" aria-controls="piece-options" aria-selected="${s===slot}" tabindex="${s===slot?'0':'-1'}" data-slot="${s}"><span aria-hidden="true">${chosen[s]?'✓':i+1}</span>${C.labels[s]}</button>`).join('');
 $('piece-options').setAttribute('aria-labelledby','slot-'+slot);
 $('piece-options').innerHTML=`<fieldset><legend class="visually-hidden">${C.labels[slot]} choices</legend><div class="piece-options-grid ${slot==='look'?'':'four-options'}">${C.pieces.filter(p=>p.slot===slot).map(p=>`<label class="piece-option ${chosen[slot]===p.id?'selected':''}"><input type="radio" name="piece-${slot}" value="${p.id}" ${chosen[slot]===p.id?'checked':''}><span class="option-art">${A.svg(p)}<span class="option-tick" aria-hidden="true">✓</span></span><strong>${esc(p.name)}</strong><small>${esc(p.note)}</small></label>`).join('')}</div></fieldset>`;
 const index=C.slots.indexOf(slot);$('next-slot').hidden=index===3;$('next-slot').textContent='Next: '+C.labels[C.slots[index+1]]+' →';$('check-look').disabled=Object.keys(chosen).length!==4;$('check-look').textContent=Object.keys(chosen).length===4?'Reveal my look ✦':`Choose ${4-Object.keys(chosen).length} more piece${Object.keys(chosen).length===3?'':'s'} to reveal`;
}
function selectSlot(s,focus=false) {const changed=slot!==s;slot=s;renderChoice();if(changed)enterOptions();if(focus)$('slot-'+s).focus();}
$('slot-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-slot]');if(b)selectSlot(b.dataset.slot,true);});
$('slot-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=C.slots.indexOf(slot);i=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;selectSlot(C.slots[i],true);});
$('outfit-preview').addEventListener('click',e=>{const b=e.target.closest('[data-select-slot]');if(b)selectSlot(b.dataset.selectSlot,true);});
$('piece-options').addEventListener('change',e=>{if(!e.target.matches('input[type="radio"]'))return;const p=C.pieces.find(p=>p.id===e.target.value&&p.slot===slot);if(!p)return;if(!started.has(day)){track('daily_style_start',{is_today:day===today});started.add(day);}chosen[slot]=p.id;state.drafts[day]={...chosen};save();revealed=false;$('game-result').hidden=true;renderChoice();animate(document.querySelector(`[data-select-slot="${slot}"] svg`),[{opacity:0,transform:'translateY(-16px) rotate(-7deg) scale(.85)'},{opacity:1,transform:'translateY(0) rotate(0) scale(1)'}]);animate(document.querySelector('.piece-option.selected .option-tick'),[{transform:'scale(.2)'},{transform:'scale(1.15)',offset:.7},{transform:'scale(1)'}]);document.querySelector(`input[value="${p.id}"]`).focus();});
$('next-slot').addEventListener('click',()=>selectSlot(C.slots[Math.min(3,C.slots.indexOf(slot)+1)],true));
$('clear-look').addEventListener('click',()=>{chosen={};state.drafts[day]={};save();slot='look';revealed=false;$('game-result').hidden=true;renderChoice();$('slot-look').focus();});
$('brief-picker').addEventListener('change',e=>{load(e.target.value);$('brief-title').setAttribute('tabindex','-1');$('brief-title').focus();});
let layerVisible=true;
function animateOutfit(){
 const host=$('runway-outfit');host.getAnimations?.({subtree:true}).forEach(a=>a.cancel());
 for(const [i,part] of ['figure','look','shoes','layer','finish'].entries())animate(host.querySelector(`[data-outfit-part="${part}"]`),[{opacity:0,transform:`translateY(${part==='figure'?0:12}px)`},{opacity:1,transform:'translateY(0)'}],{duration:500,delay:i*180,fill:'backwards'});
 animate(host.querySelector('.outfit-figure'),[{transform:'rotate(-1deg)'},{transform:'rotate(0deg)'}],{duration:1600});
}
function renderOutfit(play=true){
 $('runway-outfit').innerHTML=R.outfit(chosen,{layerVisible});
 $('runway-pieces').innerHTML=C.slots.map(slot=>{const p=C.pieces.find(p=>p.id===chosen[slot]);return `<li><span class="runway-swatch" style="background:${p.colour}" aria-hidden="true"></span><span><small>${C.labels[slot]}</small>${esc(p.name)}</span></li>`;}).join('');
 $('toggle-layer').setAttribute('aria-pressed',String(layerVisible));$('toggle-layer').textContent=layerVisible?'View without layer':'View with layer';
 $('replay-reveal').disabled=motionOff||systemReduced();if(play)animateOutfit();
}
$('replay-reveal').addEventListener('click',()=>{if(revealed){$('runway-outfit').scrollIntoView?.({block:'start',behavior:'instant'});animateOutfit();}});
$('toggle-layer').addEventListener('click',()=>{if(!revealed)return;layerVisible=!layerVisible;renderOutfit(false);$('runway-outfit').scrollIntoView?.({block:'start',behavior:'instant'});});
function reveal() {rollover();const c=C.challenge(day),s=C.score(c,chosen);if(!s.complete)return;const first=!state.results[day];state=C.record(state,day,chosen);save();renderProgress();revealed=true;layerVisible=true;$('builder-layout').hidden=true;document.querySelector('.game-brief').hidden=true;$('result-streak').textContent=C.stats(state,today).streak+' day streak';const params=new URLSearchParams({from:'style-spark',spark_day:day,...Object.fromEntries(C.slots.map(s=>['spark_'+s,chosen[s]]))});$('studio-handoff').href='../style-studio/?'+params+'#occasion'; $('game-result').hidden=false;renderOutfit();$('result-medallion').style.setProperty('--score',s.points);$('result-medallion').firstElementChild.textContent=s.points+' / 4';$('result-title').textContent=s.points===4?'Brief beautifully met.':`${s.points} of 4 details met.`;$('result-copy').textContent=s.points===4?'Your choices meet every part of this brief. Keep the look, or explore another combination.':'Your look is yours. To meet more of this particular brief, use the notes below and try a swap.';$('result-checks').innerHTML=s.checks.map(g=>`<li class="${g.met?'met':''}"><span aria-hidden="true">${g.met?'✓':'○'}</span><span>${esc(g.label)}${!g.met?`<small>${g.slot==='shoes'?'Try different shoes.':'Try a different '+C.labels[g.slot].toLowerCase().replace(/^the |^a /,'')+'.'}</small>`:''}</span></li>`).join('');$('style-tip').textContent=c.tip;$('return-note').textContent=day===today?`Tomorrow: “${C.challenge(C.shift(today,1)).title}”. A new brief at midnight (UTC+2).`:'Today’s brief is ready when you are. Find it in the recent briefs menu.';$('enquire-look').href='https://wa.me/26662790946?text='+encodeURIComponent(`Hello Jane.M, I tried the Style Spark brief “${c.title}”. My direction was ${C.slots.map(s=>C.pieces.find(p=>p.id===chosen[s]).name).join(', ')}. I would like to discuss a custom look for my occasion.`);$('share-status').textContent='';$('share-fallback').hidden=true;track(first?'daily_style_complete':'daily_style_retry',{score:s.points,is_today:day===today});$('game-result').focus();$('game-result').scrollIntoView?.({block:'start',behavior:'instant'});animate($('game-result'),[{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}]);animate($('result-medallion'),[{transform:'scale(.7) rotate(-15deg)'},{transform:'scale(1) rotate(0)'}],{duration:550});document.querySelectorAll('#result-checks li').forEach((el,i)=>animate(el,[{opacity:0,transform:'translateX(-8px)'},{opacity:1,transform:'translateX(0)'}],{delay:150+i*90}));}
$('check-look').addEventListener('click',reveal);
$('retry-look').addEventListener('click',()=>{const failed=C.score(C.challenge(day),chosen).checks.find(g=>!g.met);$('builder-layout').hidden=false;document.querySelector('.game-brief').hidden=false;selectSlot(failed?.slot||'look',true);$('game-result').hidden=true;revealed=false;});
function view(name,focus=false) {for(const n of ['home','today','saved','how']){ $(n+'-view').hidden=n!==name;document.querySelector(`[data-view="${n}"]`).setAttribute('aria-pressed',String(n===name));}if(name==='saved')renderSaved();if(focus&&name!=='today')$(name==='saved'?'lookbook-title':name==='home'?'spark-title':'how-title').focus();}
document.querySelector('.game-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)view(b.dataset.view,true);});
for(const id of ['back-today','start-playing','play-spark'])$(id).addEventListener('click',()=>{load(today);view('today');$('slot-'+slot).focus();});
function renderSaved() {const stats=C.stats(state,today);const level=stats.total>=30?'Style icon':stats.total>=15?'Trend setter':stats.total>=5?'Style explorer':stats.total>=1?'First spark':'New muse';$('level-copy').textContent=level+' · '+stats.total+' completed brief'+(stats.total===1?'':'s')+'. Your archive grows with every Spark.';$('milestones').innerHTML=[[1,'First spark'],[3,'Creative streak'],[7,'Seven looks'],[14,'Finding your flair'],[30,'Thirty sparks']].map(([n,label])=>`<span class="${stats.total>=n?'earned':''}">${stats.total>=n?'✦':'○'} ${label}<small>${Math.min(n,stats.total)} / ${n} briefs</small></span>`).join('');const dates=Object.keys(state.results).filter(d=>d<=today).sort().reverse();$('saved-grid').innerHTML=dates.length?dates.map(d=>{const r=state.results[d];return `<article class="saved-look"><div class="saved-art saved-outfit">${R.outfit(r.selection)}</div><p class="eyebrow">${pretty(d)} · ${r.points}/4 DETAILS</p><h3>${esc(C.challenge(d).title)}</h3><button type="button" data-replay="${d}">Revisit this look →</button></article>`;}).join(''):'<div class="empty-lookbook"><span aria-hidden="true">✦</span><h3>Your first look starts here.</h3><p>Complete a brief to save your outfit and begin your style diary.</p></div>';}
$('saved-grid').addEventListener('click',e=>{const b=e.target.closest('[data-replay]');if(b){load(b.dataset.replay);view('today');$('slot-'+slot).focus();}});
function shareText(){const c=C.challenge(day),s=C.score(c,chosen);return `Style Spark by Jane.M · ${pretty(day)}\n${c.title}\n${s.checks.map(g=>g.met?'✦':'○').join(' ')} ${s.points}/4 details\nYour turn: https://wearjanem.com/daily-style/?utm_source=player_share&utm_medium=social&utm_campaign=daily_style`;}
let cardBlob=null,cardUrl=null;
async function headData(){const response=await fetch('assets/thandi-head.png');if(!response.ok)throw Error('Character image unavailable');const blob=await response.blob();return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}
let embeddedHead;
async function createCard(){
 const snapshot={day,chosen:{...chosen}},canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');
 embeddedHead=embeddedHead||await headData();const image=new Image();image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(R.outfit(snapshot.chosen,{headHref:embeddedHead}));await image.decode();
 ctx.fillStyle='#fbf8f3';ctx.fillRect(0,0,1080,1350);ctx.strokeStyle='#241d22';ctx.lineWidth=5;ctx.strokeRect(28,28,1024,1294);
 ctx.fillStyle='#8f682e';ctx.font='bold 65px Georgia';ctx.fillText('Style Spark',65,112);ctx.fillStyle='#241d22';ctx.font='24px Arial';ctx.fillText('BY JANE.M',690,105);ctx.font='bold 41px Georgia';ctx.fillText(C.challenge(snapshot.day).title,65,193,950);ctx.font='23px Arial';ctx.fillText(pretty(snapshot.day)+' · My four-piece style moment',65,238);
 ctx.fillStyle='#eee4d4';ctx.beginPath();ctx.roundRect(60,280,555,825,160);ctx.fill();ctx.drawImage(image,90,290,480,870);
 for(let i=0;i<4;i++){const p=C.pieces.find(p=>p.id===snapshot.chosen[C.slots[i]]),y=426+i*153;ctx.fillStyle=p.colour;ctx.beginPath();ctx.arc(672,y-8,12,0,Math.PI*2);ctx.fill();ctx.font='17px Arial';ctx.fillStyle='#6a4553';ctx.fillText(C.labels[C.slots[i]].toUpperCase(),700,y-3);ctx.font='bold 24px Arial';ctx.fillStyle='#241d22';ctx.fillText(p.name,648,y+41,365);}
 ctx.fillStyle='#241d22';ctx.font='bold 34px Georgia';ctx.fillText(C.score(C.challenge(snapshot.day),snapshot.chosen).points+' / 4 brief details met',65,1180);ctx.font='23px Arial';ctx.fillText('Your turn: wearjanem.com/daily-style/',65,1230);ctx.font='18px Arial';ctx.fillText('Fashion. Create. Shine.  ·  Illustrated style inspiration',65,1280);
 const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Image unavailable');return blob;
}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.hidden=true;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('download-look').addEventListener('click',async()=>{if(!revealed)return;const b=$('download-look');b.disabled=true;try{cardBlob=await createCard();if(cardUrl)URL.revokeObjectURL(cardUrl);cardUrl=URL.createObjectURL(cardBlob);$('card-preview').src=cardUrl;$('card-dialog').showModal();}catch{$('share-status').textContent='The outfit card could not load. You can still share your text result.';}finally{b.disabled=false;}});
$('close-card').addEventListener('click',()=>$('card-dialog').close());
$('save-card-file').addEventListener('click',()=>{if(cardBlob){download(cardBlob,'janem-style-spark-'+day+'.png');$('card-status').textContent='Download started. Attach this card in WhatsApp to share your outfit.';track('daily_style_card_download');}});
$('share-look').addEventListener('click',async()=>{if(!revealed)return;const b=$('share-look');b.disabled=true;const text=shareText();try{
 if(navigator.share){let data={title:'Style Spark by Jane.M',text};if(navigator.canShare){try{const blob=await createCard(),file=new File([blob],'my-style-spark.png',{type:'image/png'});if(navigator.canShare({files:[file]}))data.files=[file];}catch{}}await navigator.share(data);$('share-status').textContent=data.files?'Outfit card shared.':'Result shared. Use Save outfit card to attach a picture.';track('daily_style_share',{method:data.files?'native_image':'native_text'});}
 else if(navigator.clipboard){await navigator.clipboard.writeText(text);$('share-status').textContent='Result copied. Paste it into WhatsApp. Save outfit card to attach your picture.';track('daily_style_share',{method:'copy'});}else throw Error('Copy unavailable');
 }catch(e){if(e.name!=='AbortError'){$('share-fallback').hidden=false;$('share-fallback').value=text;$('share-fallback').select();$('share-status').textContent='Copy this result to share it. Save outfit card for the picture.';}}finally{b.disabled=false;}});
$('brand-home').addEventListener('click',e=>{e.preventDefault();view('home');window.scrollTo?.({top:0});});
$('home-archive').addEventListener('click',()=>view('saved',true));
$('surprise-look').addEventListener('click',()=>{chosen=Object.fromEntries(C.slots.map(s=>{const options=C.pieces.filter(p=>p.slot===s);return[s,options[Math.floor(Math.random()*options.length)].id];}));state.drafts[day]={...chosen};save();renderChoice();animate($('live-outfit'),[{opacity:.3,transform:'scale(.95)'},{opacity:1,transform:'scale(1)'}]);track('daily_style_surprise');});
$('export-progress').addEventListener('click',()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'janem-daily-style-progress.json'));
$('clear-progress').addEventListener('click',()=>$('clear-game-dialog').showModal());$('cancel-clear').addEventListener('click',()=>$('clear-game-dialog').close());$('confirm-clear').addEventListener('click',()=>{state=C.normalise(null);save();load(today);renderProgress();renderSaved();$('clear-game-dialog').close();});
function rollover() {const next=C.dateKey();if(next===today)return;today=next;visit();picker();renderProgress();$('brief-date').textContent=day===today?'TODAY · '+pretty(day):pretty(day);if(revealed)$('return-note').textContent='A new brief is ready. Choose Today in the recent briefs menu.';}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)rollover();});setInterval(rollover,60000);
window.addEventListener('storage',e=>{if(e.key===key){try{state=C.normalise(JSON.parse(e.newValue));renderProgress();if(!$('saved-view').hidden)renderSaved();}catch{}}});
load(today);visit();renderProgress();save();
})();
