const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const W = require('./core');
assert.equal(W.risk({stage:'Sewing',due:'2026-09-08'},'2026-09-09'),'Overdue');
assert.equal(W.risk({stage:'Collected',due:'2026-09-08'},'2026-09-09'),'Complete');
assert.equal(W.risk({stage:'Sewing',due:'2026-09-15',blocker:'Fabric'},'2026-09-09'),'Blocked');
assert.equal(W.load([{stage:'Sewing',tasks:[{owner:'A',date:'2026-09-09',hours:4},{owner:'A',date:'2026-09-09',hours:2,done:true}]},{stage:'Collected',tasks:[{owner:'A',date:'2026-09-09',hours:8}]}],'A','2026-09-09'),4);
const dom=new JSDOM(fs.readFileSync(__dirname+'/index.html','utf8'),{url:'http://localhost:4175',runScripts:'outside-only'});
const w=dom.window;w.structuredClone=structuredClone;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;};
w.eval(fs.readFileSync(__dirname+'/core.js','utf8'));
w.eval(fs.readFileSync(__dirname+'/app.js','utf8'));
w.document.querySelector('[data-view="board"]').click();assert.equal(w.document.querySelectorAll('.card').length,3);
w.document.querySelector('[data-view="team"]').click();
assert.equal(w.document.querySelectorAll('td.over').length,1);
w.document.querySelector('[data-view="board"]').click();
w.document.querySelector('.card [data-job]').click();
const form=w.document.querySelector('#job-form');
form.elements.customer.value='<script>alert(1)</script>';
form.dispatchEvent(new w.Event('submit',{cancelable:true}));
assert.ok(w.localStorage.getItem('janem-workroom-v1').includes('<script>'));
assert.equal(w.document.querySelectorAll('.card script').length,0);
w.document.querySelector('#search').value='nonexistent';
w.document.querySelector('#search').dispatchEvent(new w.Event('input'));
assert.equal(w.document.querySelectorAll('.card').length,0);
console.log('Passed: SLA risk, completed work capacity, overload, editing, persistence, escaping, filtering.');

assert.deepEqual(W.normalizeSkills('Cutting, sewing, finishing'), ['Cutting','Sewing','Finishing']);
const draft=W.parseMessage('Customer: Test person\nGarment: Dress\nDelivery: 2026-09-25\nQuantity: 2');
assert.equal(draft.customer,'Test person');assert.equal(draft.due,'2026-09-25');assert.equal(draft.quantity,2);
assert.equal(W.parseMessage('[09/09/2026, 10:30] Person: Need dress tomorrow').due,undefined);
assert.equal(W.parseMessage('Delivery: 2026-02-31').due,undefined);
w.document.querySelector('#import').click();
w.document.querySelector('#wa-text').value='Customer: Test customer\nGarment: Jacket\nDelivery: 2026-09-30';
w.document.querySelector('#prepare').click();
assert.equal(form.elements.customer.value,'Test customer');assert.equal(form.elements.due.value,'2026-09-30');
assert.equal(JSON.parse(w.localStorage.getItem('janem-workroom-v1')).jobs.length,3);
w.document.querySelector('#template').click();assert.equal(w.document.querySelectorAll('.task-row').length,8);
const row=w.document.querySelector('.task-row');row.querySelector('[data-field=owner]').value='Tailor 1';
form.dispatchEvent(new w.Event('submit',{cancelable:true}));
assert.ok(w.document.querySelector('#job-warning').textContent.includes('Skill mismatch'));
w.document.querySelector('#close').click();
w.document.querySelector('[data-view="staff"]').click();
assert.equal(w.document.querySelectorAll('select[multiple]').length,0);
const staffForm=w.document.querySelector('[data-staff]');
const check=staffForm.querySelector('input[value="Measurements"]');check.checked=true;
staffForm.dispatchEvent(new w.Event('submit',{cancelable:true}));
assert.ok(JSON.parse(w.localStorage.getItem('janem-workroom-v1')).team[0].skills.includes('Measurements'));
w.document.querySelector('[data-view="revenue"]').click();
w.document.querySelector('[data-job]').click();
form.elements.price.value='1000.50';form.elements.paymentAmount.value='400.25';
form.dispatchEvent(new w.Event('submit',{cancelable:true}));
let paidJob=JSON.parse(w.localStorage.getItem('janem-workroom-v1')).jobs.find(j=>j.payments?.length);
assert.equal(paidJob.priceCents,100050);assert.equal(W.finance(paidJob).status,'Partially paid');assert.equal(W.finance(paidJob).balance,60025);
w.document.querySelector('[data-job="'+paidJob.id+'"]').click();
form.elements.paymentAmount.value='600.25';form.dispatchEvent(new w.Event('submit',{cancelable:true}));
paidJob=JSON.parse(w.localStorage.getItem('janem-workroom-v1')).jobs.find(j=>j.id===paidJob.id);
assert.equal(W.finance(paidJob).status,'Fully paid');assert.equal(paidJob.payments.length,2);
w.document.querySelector('[data-job="'+paidJob.id+'"]').click();form.elements.paymentAmount.value='1';form.dispatchEvent(new w.Event('submit',{cancelable:true}));
assert.ok(w.document.querySelector('#job-warning').textContent.includes('exceed'));
assert.equal(JSON.parse(w.localStorage.getItem('janem-workroom-v1')).jobs.find(j=>j.id===paidJob.id).payments.length,2);
assert.equal(W.finance({deposit:'Received'}).status,'Price needed');
assert.equal(W.finance({priceCents:100,payments:[]}).status,'Unpaid');
assert.throws(()=>W.cents('1.001'));assert.throws(()=>W.cents('-1'));
console.log('Passed: checkbox skills, payment history, partial/full payment, exact cents and overpayment rejection.');
w.document.querySelector('#close').click();w.document.querySelector('[data-view="board"]').click();
w.document.querySelector('#clear-filters').click();
const mover=w.document.querySelector('[data-move]'), movedId=mover.dataset.move;
mover.value='Collected';mover.dispatchEvent(new w.Event('change'));
assert.equal(w.document.querySelector('[data-card="'+movedId+'"]'),null);
w.document.querySelector('#job-scope').value='closed';w.document.querySelector('#job-scope').dispatchEvent(new w.Event('change'));
assert.equal(w.document.querySelectorAll('.card').length,1);
const reopen=w.document.querySelector('[data-move]');reopen.value='Intake';reopen.dispatchEvent(new w.Event('change'));
assert.equal(w.document.querySelectorAll('.card').length,0);
w.document.querySelector('#clear-filters').click();assert.equal(w.document.querySelectorAll('.card').length,3);
assert.equal(w.document.querySelectorAll('[data-expand][open]').length,0);
console.log('Passed: closing, closed filter, reopening and collapsed default.');
w.document.querySelector('[data-view="today"]').click();
assert.ok(w.document.querySelector('.overview-grid'));
w.document.querySelector('.attention-row').click();
assert.equal(w.document.querySelector('[data-job-panel="details"]').hidden,false);
w.document.querySelector('[data-job-tab="payments"]').click();
assert.equal(w.document.querySelector('[data-job-panel="details"]').hidden,true);
assert.equal(w.document.querySelector('[data-job-panel="payments"]').hidden,false);
form.elements.customer.dispatchEvent(new w.Event('invalid'));
assert.equal(w.document.querySelector('[data-job-panel="details"]').hidden,false);
w.document.querySelector('#close').click();
w.document.querySelector('[data-view="board"]').click();
assert.equal(w.document.querySelector('#advanced-filters').open,false);
console.log('Passed: Today overview, editor tabs, hidden-field validation and collapsed filters.');
const savedBefore=JSON.parse(w.localStorage.getItem('janem-workroom-v1'));const lifecycleId=savedBefore.jobs[0].id;
w.changeLifecycle(lifecycleId,'archive');
let lifecycleJob=JSON.parse(w.localStorage.getItem('janem-workroom-v1')).jobs[0];
assert.ok(lifecycleJob.archivedAt);assert.equal(W.active(lifecycleJob),false);assert.equal(w.matchesScope(lifecycleJob,'archived'),true);
assert.deepEqual(lifecycleJob.payments,savedBefore.jobs[0].payments);
w.changeLifecycle(lifecycleId,'trash');lifecycleJob=JSON.parse(w.localStorage.getItem('janem-workroom-v1')).jobs[0];
assert.equal(w.matchesScope(lifecycleJob,'all'),false);assert.equal(w.matchesScope(lifecycleJob,'trash'),true);
w.changeLifecycle(lifecycleId,'restore-trash');w.changeLifecycle(lifecycleId,'unarchive');
assert.equal(W.active(JSON.parse(w.localStorage.getItem('janem-workroom-v1')).jobs[0]),true);
assert.equal(w.validateBackup(savedBefore).jobs.length,3);
assert.throws(()=>w.validateBackup({jobs:[{}],team:[]}));
const malicious=structuredClone(savedBefore);malicious.jobs[0].photos=[{name:'bad',data:'javascript:alert(1)'}];assert.throws(()=>w.validateBackup(malicious));
console.log('Passed: archive/trash recovery, record preservation and backup validation.');
const receiptJob={id:'JM-1',customer:'Customer',garment:'Dress',priceCents:100000,payments:[{id:'p1',amount:40000,jobTotalCents:100000,date:'2026-09-11',method:'Cash',reference:''},{id:'p2',amount:60000,jobTotalCents:100000,date:'2026-09-11',method:'Cash',reference:''}]};
assert.ok(W.receipt(receiptJob,receiptJob.payments[0]).includes('Balance after this payment: LSL 600.00'));
assert.ok(W.receipt(receiptJob,receiptJob.payments[1]).includes('Status: Fully paid'));
receiptJob.priceCents=200000;assert.ok(W.receipt(receiptJob,receiptJob.payments[0]).includes('Job total: LSL 1000.00'));
assert.ok(w.document.querySelector('#receipt-text').value.includes('Jane.M'));
console.log('Passed: automatic receipt, partial/final balances and historical price snapshot.');
dom.window.close();
console.log('Passed: skill migration, conservative WhatsApp parsing, invalid dates, unsaved draft review, workflow template and skill mismatch enforcement.');
