(function(){
'use strict';
const C=window.PatternDrop,$=id=>document.getElementById(id),canvas=$('drop-board'),ctx=canvas.getContext('2d'),CELL=40,STORE='janem-pattern-drop-v1';
if(!ctx){$('drop-copy').textContent='This browser cannot draw the puzzle. You can still explore the other games.';$('drop-start').disabled=true;return;}
let state=C.create(),running=false,begun=false,raf=0,last=0,held=null,effect=null,soundOn=true,records={best:{classic:0,relaxed:0},today:{date:C.dayKey(),classic:0,relaxed:0}};
const audio=window.DashSound.create(window.AudioContext||window.webkitAudioContext),reduced=matchMedia('(prefers-reduced-motion: reduce)');
try{const raw=JSON.parse(localStorage.getItem(STORE)||'{}');for(const mode of ['classic','relaxed']){if(Number.isSafeInteger(raw.best?.[mode])&&raw.best[mode]>=0)records.best[mode]=raw.best[mode];if(raw.today?.date===records.today.date&&Number.isSafeInteger(raw.today[mode])&&raw.today[mode]>=0)records.today[mode]=raw.today[mode];}soundOn=localStorage.getItem('janem-pattern-drop-sound')!=='off';}catch{$('drop-storage').textContent='Score saving is unavailable. You can still play this session.';}
const track=(event,detail={})=>window.JaneMAnalytics?.track(event,{game:'pattern_drop',mode:state.mode,challenge_date:state.day,...detail});
const announce=text=>{$('drop-announcement').textContent=text;};
function save(){records.best[state.mode]=Math.max(records.best[state.mode],state.score);if(records.today.date===state.day)records.today[state.mode]=Math.max(records.today[state.mode],state.score);try{localStorage.setItem(STORE,JSON.stringify(records));}catch{$('drop-storage').textContent='Best scores are kept for this session only; browser storage is unavailable.';}}
function paintSound(){audio.set(soundOn);$('drop-sound').textContent=soundOn?'Sound on':'Sound off';$('drop-sound').setAttribute('aria-pressed',String(soundOn));$('drop-sound').setAttribute('aria-label',soundOn?'Sound effects enabled. Mute sound':'Sound effects muted. Enable sound');}
paintSound();$('drop-sound').addEventListener('click',()=>{soundOn=!soundOn;paintSound();try{localStorage.setItem('janem-pattern-drop-sound',soundOn?'on':'off');}catch{}if(soundOn){audio.unlock();audio.play('stitch');}if(running)canvas.focus({preventScroll:true});});
function mini(id){const f=C.FABRICS[id],w=f.cells[0].length*20,h=f.cells.length*20;return '<svg viewBox="0 0 100 54" role="img" aria-label="'+f.name+'">'+f.cells.map((r,y)=>r.map((v,x)=>v?'<rect x="'+((100-w)/2+x*20)+'" y="'+((54-h)/2+y*20)+'" width="18" height="18" rx="3" fill="'+f.color+'" stroke="#ffffff70" stroke-dasharray="2 3"/>':'').join('')).join('')+'</svg>';}
function sync(){
 $('drop-score').textContent=state.score.toLocaleString();$('drop-rows').textContent=Math.min(C.TARGET,state.rows)+' / 24';$('drop-level').textContent=state.level;$('drop-best').textContent=records.best[state.mode].toLocaleString();$('today-best').textContent=(records.today.date===state.day?records.today[state.mode]:0).toLocaleString();$('drop-combo').textContent=state.combo>1?state.combo+'×':state.combo===1?'1':'—';
 $('next-pieces').innerHTML=state.queue.slice(0,3).map(id=>'<div class="next-piece">'+mini(id)+'</div>').join('');
 $('mix-date').textContent='Fabric mix · '+new Date(state.day+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})+' · UTC+2';
 const stage=Math.min(2,Math.floor(state.rows/8)),rows=state.rows>=24?8:state.rows%8,fill=rows/8*220;
 $('garment-fill').setAttribute('y',220-fill);$('garment-fill').setAttribute('height',fill);$('garment-colour').setAttribute('fill',['#bd7886','#6e9985','#bd965a'][stage]);$('garment-caption').textContent='Look '+(stage+1)+' · '+['The rose edit','The sage edit','The golden edit'][stage];
 document.querySelectorAll('#collection-progress li').forEach((li,i)=>{const n=Math.max(0,Math.min(8,state.rows-i*8));li.classList.toggle('complete',n===8);li.querySelector('b').textContent=n===8?'✓ Made':n+' / 8';});
}
function block(x,y,id,ghost=false){const px=x*CELL,py=y*CELL;ctx.save();ctx.beginPath();ctx.roundRect(px+2,py+2,CELL-4,CELL-4,5);if(ghost){ctx.strokeStyle=C.FABRICS[id].color;ctx.setLineDash([3,4]);ctx.lineWidth=2;ctx.stroke();}else{ctx.fillStyle=C.FABRICS[id].color;ctx.fill();ctx.strokeStyle='#10251e60';ctx.lineWidth=1;ctx.setLineDash([2,3]);ctx.strokeRect(px+6,py+6,CELL-12,CELL-12);ctx.setLineDash([]);ctx.strokeStyle='#fff6df55';ctx.beginPath();if(id%3===0){ctx.moveTo(px+7,py+CELL-7);ctx.lineTo(px+CELL-7,py+7);}else if(id%3===1){ctx.moveTo(px+7,py+13);ctx.lineTo(px+CELL-7,py+13);ctx.moveTo(px+7,py+25);ctx.lineTo(px+CELL-7,py+25);}else{ctx.arc(px+20,py+20,5,0,Math.PI*2);}ctx.stroke();}ctx.restore();}
function paint(now=0){ctx.fillStyle='#18211e';ctx.fillRect(0,0,320,640);ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;for(let x=0;x<=C.W;x++){ctx.beginPath();ctx.moveTo(x*CELL,0);ctx.lineTo(x*CELL,640);ctx.stroke();}for(let y=0;y<=C.H;y++){ctx.beginPath();ctx.moveTo(0,y*CELL);ctx.lineTo(320,y*CELL);ctx.stroke();}
 state.board.forEach((r,y)=>r.forEach((v,x)=>{if(v)block(x,y,v-1);}));
 if(state.status==='playing'){const a=state.active,gy=C.ghostY(state);for(const [y,row] of a.cells.entries())for(const [x,v] of row.entries())if(v){block(a.x+x,gy+y,a.id,true);block(a.x+x,a.y+y,a.id);}}
 if(effect&&!reduced.matches){const alpha=Math.max(0,1-(now-effect.start)/250);if(alpha){ctx.fillStyle='rgba(242,215,155,'+alpha*.4+')';effect.lines.forEach(y=>ctx.fillRect(0,y*CELL,320,CELL));}else effect=null;}
 ctx.strokeStyle='#bc8e4070';ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(0,2*CELL);ctx.lineTo(320,2*CELL);ctx.stroke();ctx.setLineDash([]);
}
function overlay(title,copy,kicker,button){$('drop-title').textContent=title;$('drop-copy').textContent=copy;$('drop-kicker').textContent=kicker;$('drop-start').textContent=button;$('drop-overlay').hidden=false;$('drop-mode-label').hidden=true;$('drop-restart').hidden=true;$('drop-share').hidden=true;$('drop-share-status').textContent='';}
function stop(){running=false;held=null;last=0;cancelAnimationFrame(raf);audio.stop();$('drop-pause').disabled=true;paint();}
function finish(){stop();save();sync();const won=state.status==='won';audio.play(won?'won':'lost');overlay(won?'A collection, made by you.':'Room for another idea.',won?'Three looks, 24 rows and '+state.score.toLocaleString()+' points. Beautifully pieced together.':'You stitched '+state.rows+' rows for '+state.score.toLocaleString()+' points. Leave space for the long pieces and use the landing outline to plan ahead.',won?'COLLECTION COMPLETE':'RUN COMPLETE','Play again →');$('drop-mode-label').hidden=false;$('drop-share').hidden=false;track(won?'pattern_drop_complete':'pattern_drop_game_over',{score:state.score,rows:state.rows});announce($('drop-title').textContent+' '+$('drop-copy').textContent);$('drop-start').focus({preventScroll:true});}
function events(){for(const e of state.events){if(e.type==='clear'){effect={lines:e.lines,start:performance.now()};const message=e.count+' row'+(e.count===1?'':'s')+' stitched · +'+e.points+(e.combo>1?' · '+e.combo+'× chain':'');$('drop-feedback').textContent=message;announce(message);audio.play(e.count>1?'delivered':'supply');track('pattern_drop_rows_cleared',{rows:e.count,chain:e.combo,score:state.score});save();}else if(e.type==='lock'){audio.play('stitch');save();}}
 state.events=[];sync();if(state.status!=='playing')finish();}
function action(kind){if(!running)return;let changed=false;if(kind==='left')changed=C.move(state,-1);if(kind==='right')changed=C.move(state,1);if(kind==='rotate'){changed=C.rotate(state);if(changed)audio.play('stitch');}if(kind==='soft')changed=C.softDrop(state);if(kind==='drop'){C.hardDrop(state);changed=true;}events();paint();return changed;}
function loop(now){if(!running)return;if(!last)last=now;const dt=Math.min(now-last,100);last=now;if(held&&now>=held.next){action(held.action);if(held)held.next=now+85;}if(!running)return;C.tick(state,dt);if(state.events.length)events();if(!running)return;paint(now);raf=requestAnimationFrame(loop);}
function begin(){if(running)return;const resume=begun&&state.status==='playing'&&$('drop-mode-label').hidden;audio.unlock();if(!resume){state=C.create(C.dayKey(),$('drop-mode').value);if(records.today.date!==state.day)records.today={date:state.day,classic:0,relaxed:0};$('drop-feedback').textContent='Make a full row, leave no gaps.';}begun=true;state.events=[];effect=null;sync();$('drop-overlay').hidden=true;$('drop-pause').disabled=false;running=true;last=0;audio.play('start');canvas.focus({preventScroll:true});document.querySelector('.drop-play').scrollIntoView?.({block:'start',behavior:'instant'});track(resume?'pattern_drop_resume':'pattern_drop_start');announce('Puzzle started. Use the arrows to move, up to turn, Space to place.');raf=requestAnimationFrame(loop);}
function pause(reason='Take your time.'){if(!running)return;stop();overlay('A moment to think.',reason+' Your fabric will wait while you stay on this page.','PUZZLE PAUSED','Resume →');$('drop-restart').hidden=false;announce('Puzzle paused.');$('drop-start').focus({preventScroll:true});track('pattern_drop_pause');}
$('drop-start').addEventListener('click',begin);$('drop-pause').addEventListener('click',()=>pause());$('drop-restart').addEventListener('click',()=>{begun=false;begin();});$('drop-mode').addEventListener('change',()=>{const mode=$('drop-mode').value;$('drop-best').textContent=records.best[mode].toLocaleString();$('today-best').textContent=records.today[mode].toLocaleString();});
const keyActions={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'rotate',ArrowDown:'soft',' ':'drop',a:'left',d:'right',w:'rotate',s:'soft'};
canvas.addEventListener('keydown',e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;if(!running)return;if(key==='Escape'||key==='p'){e.preventDefault();pause();return;}const kind=keyActions[key];if(kind){e.preventDefault();if(e.repeat&&['drop','rotate'].includes(kind))return;action(kind);}});
for(const b of document.querySelectorAll('[data-action]')){b.addEventListener('pointerdown',e=>{if(!running)return;e.preventDefault();b.setPointerCapture(e.pointerId);action(b.dataset.action);if(running){canvas.focus({preventScroll:true});if(['left','right','soft'].includes(b.dataset.action))held={action:b.dataset.action,next:performance.now()+260};}});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{held=null;});b.addEventListener('click',e=>{if(e.detail===0)action(b.dataset.action);});}
canvas.addEventListener('blur',e=>{if(running&&!e.relatedTarget?.closest('.game-tools,.drop-controls'))pause('Paused while you use another control.');});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('Paused while you were away.');});window.addEventListener('blur',()=>pause('Paused while you were away.'));
$('drop-share').addEventListener('click',async()=>{const text='I scored '+state.score+' and stitched '+state.rows+' rows in Jane.M Pattern Drop ('+state.mode+')! Try today’s fabric puzzle: https://wearjanem.com/pattern-drop/';try{await navigator.clipboard.writeText(text);$('drop-share-status').textContent='Score copied. Paste it into your chat.';track('pattern_drop_share',{score:state.score,rows:state.rows});}catch{$('drop-share-status').textContent=text;}});
sync();paint();
})();
